
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Visita','com_ereservas.visita','{"special":{"dbtable":"#__ereservas_visita","key":"id","type":"Visita","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/visita.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"idioma","targetTable":"#__ereservas_idioma","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_tipo_visita","targetTable":"#__ereservas_tipo_visita","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"guia","targetTable":"#__ereservas_guias","targetColumn":"id","displayColumn":"nombre"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.visita')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Visita', 
	`table` = '{"special":{"dbtable":"#__ereservas_visita","key":"id","type":"Visita","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/visita.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"idioma","targetTable":"#__ereservas_idioma","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_tipo_visita","targetTable":"#__ereservas_tipo_visita","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"guia","targetTable":"#__ereservas_guias","targetColumn":"id","displayColumn":"nombre"}]}'
WHERE (`type_alias` = 'com_ereservas.visita');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Tipo visita','com_ereservas.tipovisita','{"special":{"dbtable":"#__ereservas_tipo_visita","key":"id","type":"Tipovisita","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/tipovisita.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.tipovisita')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Tipo visita', 
	`table` = '{"special":{"dbtable":"#__ereservas_tipo_visita","key":"id","type":"Tipo visita","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/tipovisita.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.tipovisita');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Sala','com_ereservas.sala','{"special":{"dbtable":"#__ereservas_sala","key":"id","type":"Sala","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/sala.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.sala')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Sala', 
	`table` = '{"special":{"dbtable":"#__ereservas_sala","key":"id","type":"Sala","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/sala.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.sala');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Idioma','com_ereservas.idioma','{"special":{"dbtable":"#__ereservas_idioma","key":"id","type":"Idioma","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/idioma.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.idioma')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Idioma', 
	`table` = '{"special":{"dbtable":"#__ereservas_idioma","key":"id","type":"Idioma","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/idioma.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.idioma');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Pais','com_ereservas.pais','{"special":{"dbtable":"#__ereservas_pais","key":"id","type":"Pais","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/pais.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.pais')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Pais', 
	`table` = '{"special":{"dbtable":"#__ereservas_pais","key":"id","type":"Pais","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/pais.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.pais');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Tipo cliente','com_ereservas.tipocliente','{"special":{"dbtable":"#__ereservas_tipo_cliente","key":"id","type":"Tipocliente","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/tipocliente.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.tipocliente')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Tipo cliente', 
	`table` = '{"special":{"dbtable":"#__ereservas_tipo_cliente","key":"id","type":"Tipo cliente","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/tipocliente.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.tipocliente');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Reserva','com_ereservas.reserva','{"special":{"dbtable":"#__ereservas_reserva","key":"id","type":"Reserva","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/reserva.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_visita","targetTable":"#__ereservas_visita","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_idioma","targetTable":"#__ereservas_idioma","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_usuario","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"},{"sourceColumn":"id_pais","targetTable":"#__ereservas_pais","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_tipo_cliente","targetTable":"#__ereservas_tipo_cliente","targetColumn":"id","displayColumn":"nombre"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.reserva')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Reserva', 
	`table` = '{"special":{"dbtable":"#__ereservas_reserva","key":"id","type":"Reserva","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/reserva.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_visita","targetTable":"#__ereservas_visita","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_idioma","targetTable":"#__ereservas_idioma","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_usuario","targetTable":"users","targetColumn":"users_id","displayColumn":"users_name"},{"sourceColumn":"id_pais","targetTable":"#__ereservas_pais","targetColumn":"id","displayColumn":"nombre"},{"sourceColumn":"id_tipo_cliente","targetTable":"#__ereservas_tipo_cliente","targetColumn":"id","displayColumn":"nombre"}]}'
WHERE (`type_alias` = 'com_ereservas.reserva');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Guia','com_ereservas.guia','{"special":{"dbtable":"#__ereservas_guias","key":"id","type":"Guia","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/guia.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.guia')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Guia', 
	`table` = '{"special":{"dbtable":"#__ereservas_guias","key":"id","type":"Guia","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/guia.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.guia');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Calendario','com_ereservas.calendario','{"special":{"dbtable":"#__ereservas_calendario","key":"id","type":"Calendario","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/calendario.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_tipo_visita","targetTable":"#__ereservas_tipo_visita","targetColumn":"id","displayColumn":"nombre"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.calendario')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Calendario', 
	`table` = '{"special":{"dbtable":"#__ereservas_calendario","key":"id","type":"Calendario","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/calendario.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_tipo_visita","targetTable":"#__ereservas_tipo_visita","targetColumn":"id","displayColumn":"nombre"}]}'
WHERE (`type_alias` = 'com_ereservas.calendario');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Factura','com_ereservas.factura','{"special":{"dbtable":"#__ereservas_factura","key":"id","type":"Factura","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/factura.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_reserva","targetTable":"#__ereservas_reserva","targetColumn":"id","displayColumn":"id"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.factura')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Factura', 
	`table` = '{"special":{"dbtable":"#__ereservas_factura","key":"id","type":"Factura","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/factura.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"id_reserva","targetTable":"#__ereservas_reserva","targetColumn":"id","displayColumn":"id"}]}'
WHERE (`type_alias` = 'com_ereservas.factura');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Servicio semanal','com_ereservas.serviciosemanal','{"special":{"dbtable":"#__ereservas_servicio_semanal","key":"id","type":"Serviciosemanal","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/serviciosemanal.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.serviciosemanal')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Servicio semanal', 
	`table` = '{"special":{"dbtable":"#__ereservas_servicio_semanal","key":"id","type":"Servicio semanal","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/serviciosemanal.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.serviciosemanal');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Fechas apertura','com_ereservas.fechasapertura','{"special":{"dbtable":"#__ereservas_fechas_apertura","key":"id","type":"Fechasapertura","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/fechasapertura.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.fechasapertura')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Fechas apertura', 
	`table` = '{"special":{"dbtable":"#__ereservas_fechas_apertura","key":"id","type":"Fechas apertura","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/fechasapertura.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.fechasapertura');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Cierre','com_ereservas.cierre','{"special":{"dbtable":"#__ereservas_cierres","key":"id","type":"Cierre","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/cierre.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.cierre')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Cierre', 
	`table` = '{"special":{"dbtable":"#__ereservas_cierres","key":"id","type":"Cierre","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/cierre.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.cierre');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Cancelacione','com_ereservas.cancelacione','{"special":{"dbtable":"#__ereservas_cancelaciones","key":"id","type":"Cancelacione","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/cancelacione.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.cancelacione')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Cancelacione', 
	`table` = '{"special":{"dbtable":"#__ereservas_cancelaciones","key":"id","type":"Cancelacione","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/cancelacione.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.cancelacione');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Lista espera','com_ereservas.listaespera','{"special":{"dbtable":"#__ereservas_lista_espera","key":"id","type":"Listaespera","prefix":"EreservasTable"}}', '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/listaespera.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_ereservas.listaespera')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Lista espera', 
	`table` = '{"special":{"dbtable":"#__ereservas_lista_espera","key":"id","type":"Lista espera","prefix":"EreservasTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_ereservas\/models\/forms\/listaespera.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_ereservas.listaespera');
